### ISSUE TITLE
plam pvg100 pepito

### ISSUE THREAD

**Issue by SnowCore8** [deadman96385/android_kernel_palm_pepito#1]
这套源码能否正常使用

**Comment by SnowCore8** [comment]
Can this source code work normally?

**Comment by deadman96385** [comment]
No this is not complete, it was made in case Palm actually released their full kernel source instead of just the broken one currently. This is the qualcomm brand/tag that they used as the base for the phone. It is missing all device specific changes.

**Comment by SnowCore8** [comment]
OK, I see. Thank you for your answer.
